// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComfyBot.Migrations
{
    [DbContext(typeof(ComfyContext))]
    [Migration("20230409203610_AddScheduledEventFields")]
    partial class AddScheduledEventFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("ScheduledEvent", b =>
                {
                    b.Property<int>("ScheduledEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("End")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Recurrence")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecurrenceValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RemindMinutesBefore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("Start")
                        .HasColumnType("TEXT");

                    b.HasKey("ScheduledEventId");

                    b.ToTable("ScheduledEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
